export type AutorMock = {
  id: string;
  nombre: string;
  partido: string;
  cargo: string;
  foto_url: string | null;
  email: string;
  iniciativas_count: number;
};

export const MOCK_AUTORES: AutorMock[] = [
  {
    id: "a1",
    nombre: "Carlos Andrés Mejía Ruiz",
    partido: "Pacto Histórico",
    cargo: "Concejal",
    foto_url: null,
    email: "carlos.mejia@concejodemedellin.gov.co",
    iniciativas_count: 8,
  },
  {
    id: "a2",
    nombre: "María Fernanda López Gómez",
    partido: "Centro Democrático",
    cargo: "Concejal",
    foto_url: null,
    email: "maria.lopez@concejodemedellin.gov.co",
    iniciativas_count: 6,
  },
  {
    id: "a3",
    nombre: "Juan Esteban Ríos Cardona",
    partido: "Partido Liberal",
    cargo: "Concejal",
    foto_url: null,
    email: "juan.rios@concejodemedellin.gov.co",
    iniciativas_count: 7,
  },
  {
    id: "a4",
    nombre: "Laura Catalina Ospina Vélez",
    partido: "Partido Verde",
    cargo: "Concejal",
    foto_url: null,
    email: "laura.ospina@concejodemedellin.gov.co",
    iniciativas_count: 9,
  },
  {
    id: "a5",
    nombre: "Andrés Felipe Restrepo Muñoz",
    partido: "Partido Conservador",
    cargo: "Concejal",
    foto_url: null,
    email: "andres.restrepo@concejodemedellin.gov.co",
    iniciativas_count: 5,
  },
  {
    id: "a6",
    nombre: "Diana Marcela Herrera Álvarez",
    partido: "Colombia Humana",
    cargo: "Concejal",
    foto_url: null,
    email: "diana.herrera@concejodemedellin.gov.co",
    iniciativas_count: 7,
  },
  {
    id: "a7",
    nombre: "Santiago Bedoya Zapata",
    partido: "Cambio Radical",
    cargo: "Concejal",
    foto_url: null,
    email: "santiago.bedoya@concejodemedellin.gov.co",
    iniciativas_count: 4,
  },
  {
    id: "a8",
    nombre: "Valentina Giraldo Montoya",
    partido: "Pacto Histórico",
    cargo: "Concejal",
    foto_url: null,
    email: "valentina.giraldo@concejodemedellin.gov.co",
    iniciativas_count: 6,
  },
  {
    id: "a9",
    nombre: "Jorge Iván Castaño Pérez",
    partido: "Partido Liberal",
    cargo: "Concejal",
    foto_url: null,
    email: "jorge.castano@concejodemedellin.gov.co",
    iniciativas_count: 5,
  },
  {
    id: "a10",
    nombre: "Natalia Andrea Uribe Sánchez",
    partido: "Centro Democrático",
    cargo: "Concejal",
    foto_url: null,
    email: "natalia.uribe@concejodemedellin.gov.co",
    iniciativas_count: 4,
  },
  {
    id: "a11",
    nombre: "Ricardo Esteban Henao Correa",
    partido: "Partido Conservador",
    cargo: "Concejal",
    foto_url: null,
    email: "ricardo.henao@concejodemedellin.gov.co",
    iniciativas_count: 3,
  },
  {
    id: "a12",
    nombre: "Camila Andrea Salazar Tobón",
    partido: "Partido Verde",
    cargo: "Concejal",
    foto_url: null,
    email: "camila.salazar@concejodemedellin.gov.co",
    iniciativas_count: 6,
  },
  {
    id: "a13",
    nombre: "Felipe Augusto Ramírez Londoño",
    partido: "Cambio Radical",
    cargo: "Concejal",
    foto_url: null,
    email: "felipe.ramirez@concejodemedellin.gov.co",
    iniciativas_count: 3,
  },
  {
    id: "a14",
    nombre: "Isabela María Arango Duque",
    partido: "Colombia Humana",
    cargo: "Concejal",
    foto_url: null,
    email: "isabela.arango@concejodemedellin.gov.co",
    iniciativas_count: 5,
  },
  {
    id: "a15",
    nombre: "Sebastián David Posada Gil",
    partido: "Pacto Histórico",
    cargo: "Concejal",
    foto_url: null,
    email: "sebastian.posada@concejodemedellin.gov.co",
    iniciativas_count: 4,
  },
];
