import type { TerritoryData } from "./types";

export const TERRITORIES: TerritoryData[] = [
  // Comunas
  {
    codigo: "1",
    nombre: "Popular",
    tipo: "comuna",
    poblacion: 130_095,
    area_km2: 3.09,
  },
  {
    codigo: "2",
    nombre: "Santa Cruz",
    tipo: "comuna",
    poblacion: 111_452,
    area_km2: 2.19,
  },
  {
    codigo: "3",
    nombre: "Manrique",
    tipo: "comuna",
    poblacion: 160_235,
    area_km2: 5.49,
  },
  {
    codigo: "4",
    nombre: "Aranjuez",
    tipo: "comuna",
    poblacion: 162_415,
    area_km2: 4.87,
  },
  {
    codigo: "5",
    nombre: "Castilla",
    tipo: "comuna",
    poblacion: 149_751,
    area_km2: 6.09,
  },
  {
    codigo: "6",
    nombre: "Doce de Octubre",
    tipo: "comuna",
    poblacion: 194_925,
    area_km2: 3.81,
  },
  {
    codigo: "7",
    nombre: "Robledo",
    tipo: "comuna",
    poblacion: 175_114,
    area_km2: 9.42,
  },
  {
    codigo: "8",
    nombre: "Villa Hermosa",
    tipo: "comuna",
    poblacion: 137_530,
    area_km2: 5.79,
  },
  {
    codigo: "9",
    nombre: "Buenos Aires",
    tipo: "comuna",
    poblacion: 136_774,
    area_km2: 5.98,
  },
  {
    codigo: "10",
    nombre: "La Candelaria",
    tipo: "comuna",
    poblacion: 85_321,
    area_km2: 7.47,
  },
  {
    codigo: "11",
    nombre: "Laureles-Estadio",
    tipo: "comuna",
    poblacion: 122_243,
    area_km2: 7.41,
  },
  {
    codigo: "12",
    nombre: "La América",
    tipo: "comuna",
    poblacion: 96_894,
    area_km2: 3.98,
  },
  {
    codigo: "13",
    nombre: "San Javier",
    tipo: "comuna",
    poblacion: 138_063,
    area_km2: 7.46,
  },
  {
    codigo: "14",
    nombre: "El Poblado",
    tipo: "comuna",
    poblacion: 130_124,
    area_km2: 14.12,
  },
  {
    codigo: "15",
    nombre: "Guayabal",
    tipo: "comuna",
    poblacion: 97_479,
    area_km2: 7.67,
  },
  {
    codigo: "16",
    nombre: "Belén",
    tipo: "comuna",
    poblacion: 200_543,
    area_km2: 8.83,
  },
  // Corregimientos
  {
    codigo: "50",
    nombre: "San Sebastián de Palmitas",
    tipo: "corregimiento",
    poblacion: 5_614,
    area_km2: 57.43,
  },
  {
    codigo: "60",
    nombre: "San Cristóbal",
    tipo: "corregimiento",
    poblacion: 75_482,
    area_km2: 49.67,
  },
  {
    codigo: "70",
    nombre: "Altavista",
    tipo: "corregimiento",
    poblacion: 39_473,
    area_km2: 27.41,
  },
  {
    codigo: "80",
    nombre: "San Antonio de Prado",
    tipo: "corregimiento",
    poblacion: 107_218,
    area_km2: 50.83,
  },
  {
    codigo: "90",
    nombre: "Santa Elena",
    tipo: "corregimiento",
    poblacion: 17_357,
    area_km2: 70.37,
  },
];
